package com.lja.oa.dao;

import com.lja.oa.pojo.Org;
import com.lja.oa.pojo.Orgs;

import java.util.List;
import java.util.Map;

public interface OrgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated Mon Nov 06 15:48:01 CST 2017
     */
    int deleteByPrimaryKey(Long orgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated Mon Nov 06 15:48:01 CST 2017
     */
    int insert(Org record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated Mon Nov 06 15:48:01 CST 2017
     */
    int insertSelective(Org record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated Mon Nov 06 15:48:01 CST 2017
     */
    Org selectByPrimaryKey(Long orgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated Mon Nov 06 15:48:01 CST 2017
     */
    int updateByPrimaryKeySelective(Org record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated Mon Nov 06 15:48:01 CST 2017
     */
    int updateByPrimaryKey(Org record);

    public List<Org> queryOrgListByOrgParentId(Map<String, Object> map);

    List<Org> getPage(Map<String, Object> paramMap);

    int getCount(Map<String, Object> paramMap);

    Orgs queryOrgById(int orgId);
}