package com.lja.oa.dao;

import com.lja.oa.pojo.Role;

import java.util.List;
import java.util.Map;

public interface RoleMapper {
    public List<Role> queryRolePage(Map<String, Object> paramMap);
    public int countTotal(Map<String, Object> paramMap);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Fri Apr 07 17:31:48 CST 2017
     */
    int deleteByPrimaryKey(Long roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Fri Apr 07 17:31:48 CST 2017
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Fri Apr 07 17:31:48 CST 2017
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Fri Apr 07 17:31:48 CST 2017
     */
    Role selectByPrimaryKey(Long roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Fri Apr 07 17:31:48 CST 2017
     */
    int updateByPrimaryKeySelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbggenerated Fri Apr 07 17:31:48 CST 2017
     */
    int updateByPrimaryKey(Role record);
    public List<Role> getRoleList();
    public List<Role> queryRoleList();
}
