package com.lja.oa.dao;

import com.lja.oa.pojo.RoleOrgRel;

public interface RoleOrgRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_org_rel
     *
     * @mbggenerated Fri May 19 11:12:06 CST 2017
     */
    int deleteByPrimaryKey(Long roleOrgRelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_org_rel
     *
     * @mbggenerated Fri May 19 11:12:06 CST 2017
     */
    int insert(RoleOrgRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_org_rel
     *
     * @mbggenerated Fri May 19 11:12:06 CST 2017
     */
    int insertSelective(RoleOrgRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_org_rel
     *
     * @mbggenerated Fri May 19 11:12:06 CST 2017
     */
    RoleOrgRel selectByPrimaryKey(Long roleOrgRelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_org_rel
     *
     * @mbggenerated Fri May 19 11:12:06 CST 2017
     */
    int updateByPrimaryKeySelective(RoleOrgRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_org_rel
     *
     * @mbggenerated Fri May 19 11:12:06 CST 2017
     */
    int updateByPrimaryKey(RoleOrgRel record);

	void delOrgRoleRel(RoleOrgRel rel);
}