package com.lja.oa.service;

import com.lja.oa.pojo.Menu;
import com.lja.oa.pojo.Menus;
import com.lja.oa.pojo.RoleMenuRel;

import java.util.List;
import java.util.Map;

public interface IMenuService {
    public Map<String, Object> queryMenuPage(Map<String, Object> paramMap);
    //展示树时只查询菜单类型为目录的
    public List<Menu> queryMenuDirListByMenuParentId(Map<String, Object> paramMap);
    public Menus selectMenusByPrimaryKey(long menuId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated Mon Mar 13 16:11:18 CST 2017
     */
    int deleteByPrimaryKey(Long menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated Mon Mar 13 16:11:18 CST 2017
     */
    int insert(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated Mon Mar 13 16:11:18 CST 2017
     */
    int insertSelective(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated Mon Mar 13 16:11:18 CST 2017
     */
    Menu selectByPrimaryKey(Long menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated Mon Mar 13 16:11:18 CST 2017
     */
    int updateByPrimaryKeySelective(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbggenerated Mon Mar 13 16:11:18 CST 2017
     */
    int updateByPrimaryKey(Menu record);
    public List<Menu> queryMenuListByMenuParentId(Map<String, Object> paramMap);
    public void addRoleMenuRel(RoleMenuRel rel);
}
